FROM node:16-alpine

WORKDIR reactapp

# Install some depenendencies
COPY package.json .
RUN npm install

# copy files into container
# we can remove this instruction when using volume to access our local files
COPY . . 

# Default command
CMD ["npm", "start"]
